# Generated by Django 4.2 on 2023-04-29 09:21

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
