# Generated by Django 4.2 on 2023-04-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я автора")),
                ('lastName', models.CharField(max_length=100, verbose_name='Прізвище автора')),
                ('email', models.CharField(max_length=255, verbose_name='Електрона пошта')),
            ],
        ),
    ]
